ip: 127.0.0.1
port: 21818
db_host: "gsmysql"
db_port: 3306
db_user: "root"
db_password: '123456'
db_name: web
allow_old_password: false
auto_reg: true
# allow_ips:
#  - 127.0.0.1
#  - 192.168.10.3
point_fix: 0
max_client_count: 500
pc_max_client_count: 3
